""" Unit tests for survey/response business logic (mocked DB) """

import pytest
from re import escape
from datetime import date, datetime
from unittest.mock import Mock, patch
from pydantic import ValidationError
from botocore.exceptions import BotoCoreError
from employee_survey_analyzer.surveys.models import Survey, Response
from employee_survey_analyzer.surveys import services
from employee_survey_analyzer.representations import InvalidAuthorizationError, SurveyInvalidDateRangeError, SurveyNotFoundError, SurveyUnavailableError, SurveyUnmodifiableError

# mock method to set id since it is autogenerated by database
def _mock_create_survey_id(record: Survey):
    record.id = 1

# specifically for create_response() since the timestamp is also autogenerated by database
def _mock_set_created_at(record: Response):
    record.id = 1
    record.created_at = datetime(2026, 9, 1)

@pytest.mark.parametrize("row, status", [
    ({"id": 1, "title": "Survey", "prompt": "How are you?", "department": "Sales", 
     "open_date": "2026-07-20", "close_date": "2026-10-20"}, "open"),   # "today" between open and close dates
    ({"id": 2, "title": "Survey", "prompt": "How are you?", "department": "Sales", 
     "open_date": "2026-07-20", "close_date": "2026-08-20"}, "closed"), # "today" past close date
    ({"id": 3, "title": "Survey", "prompt": "How are you?", "department": "Sales", 
     "open_date": "2026-09-20", "close_date": "2026-10-20"}, "draft")   # "today" before open date
])
@patch("employee_survey_analyzer.surveys.services.date")
def test_get_all_surveys_status(mock_date, row, status):
    # mock "today" so that test doesn't break in the future when compared to input data dates
    mock_date.today.return_value = date(2026, 9, 1)

    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        mock_store.get_all_surveys.return_value = [row]

        surveys = services.get_all_surveys()

        assert len(surveys) == 1
        assert surveys[0]["status"] == status

        mock_store.get_all_surveys.assert_called_once()

def test_get_all_surveys_multiple(sample_survey):
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        survey_list = [{**sample_survey, "id": i} for i in range(3)]
        mock_store.get_all_surveys.return_value = survey_list

        surveys = services.get_all_surveys()

        assert len(surveys) == 3
        assert surveys[0]["title"] == "Mid-Year Check-in"
        assert surveys[1]["department"] == "Marketing"

        mock_store.get_all_surveys.assert_called_once()

def test_get_all_surveys_none():
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        survey_list = []
        mock_store.get_all_surveys.return_value = survey_list

        surveys = services.get_all_surveys()

        assert len(surveys) == 0

        mock_store.get_all_surveys.assert_called_once()

def test_get_survey_by_id_success(sample_survey):
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 1
        mock_store.get_survey_by_id.return_value = sample_survey

        survey = services.get_survey_by_id(1)

        assert survey.id == 1
        assert survey.title == "Mid-Year Check-in"
        assert survey.prompt == "How supported do you feel by your manager these past 6 months?"
        assert survey.department == "Marketing"
        assert survey.open_date == date(2026, 6, 20)
        assert survey.close_date == date(2026, 10, 20)

        mock_store.get_survey_by_id.assert_called_once()

def test_get_survey_by_id_not_found(sample_survey):
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 2
        mock_store.get_survey_by_id.return_value = None

        with pytest.raises(SurveyNotFoundError):
            services.get_survey_by_id(1)

@patch("employee_survey_analyzer.surveys.services.store")
def test_generate_survey_summary(mock_store, sample_survey, sample_responses):
    # allow dict representation of sample_survey to have a responses field (from database relationship)
    mock_survey = Mock()
    mock_survey.configure_mock(**sample_survey)
    mock_survey.responses = sample_responses
    mock_store.get_survey_by_id.return_value = mock_survey

    with patch("employee_survey_analyzer.surveys.services.summarize_key_phrases") as mock_key_phrases:
        expected_key_phrases = [
            {
                "phrase": "my manager",
                "count": 2
            },
            {
                "phrase": "my concerns",
                "count": 2
            },
            {
                "phrase": "onboarding",
                "count": 1
            },
            {
                "phrase": "a leave",
                "count": 1
            }
        ]
        mock_key_phrases.return_value = expected_key_phrases

        summary = services.generate_survey_summary(1)

        assert summary["survey_id"] == 1
        assert summary["response_count"] == 2
        assert summary["sentiment_distribution"]["POSITIVE"] == 0.5
        assert summary["sentiment_distribution"]["NEGATIVE"] == 0.5
        assert summary["sentiment_distribution"]["NEUTRAL"] == 0
        assert summary["sentiment_distribution"]["MIXED"] == 0
        assert summary["top_phrases"] == expected_key_phrases

        mock_store.get_survey_by_id.assert_called_once()

def test_create_survey_success(sample_survey):
    # patch the store.create_survey() with mocked version that doesn't do anything
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        mock_store.create_survey.side_effect = _mock_create_survey_id
        survey = services.create_survey(sample_survey)

        assert survey.id == 1
        assert survey.title == "Mid-Year Check-in"
        assert survey.prompt == "How supported do you feel by your manager these past 6 months?"
        assert survey.department == "Marketing"
        assert survey.open_date == date(2026, 6, 20)
        assert survey.close_date == date(2026, 10, 20)

        mock_store.create_survey.assert_called_once()
        mock_store.commit_change.assert_called_once()


@pytest.mark.parametrize("row, error", [
    ({"title": "Survey", "prompt": "Prompt?", "department": "Sales", 
     "open_date": "2026-07-20", "close_date": "2026-10-20"}, ValidationError), # prompt too short
    ({"title": "Survey", "prompt": "How are you?", "department": "Sales", 
     "open_date": "2026-07-20", "close_date": "2026-05-20"}, SurveyInvalidDateRangeError), # invalid date range
    ({"title": "Survey", "prompt": "How are you?", "department": "Sales", 
     "open_date": "2026-07-20", "close_date": "2026-50-20"}, ValidationError), # invalid date
    ({"title": "Survey", "prompt": "How are you?", "department": "Sales", 
     "open_date": "2026-07-20", "close_date": "2026-50-20", "test": "test"}, ValidationError) # extra field
])
def test_create_survey_invalid(row, error):
    with pytest.raises(error):
        with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
            mock_store.create_survey.side_effect = _mock_create_survey_id
            services.create_survey(row)

def test_update_survey_success(sample_survey):
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 1
        mock_survey = Mock()
        mock_survey.configure_mock(**sample_survey)
        mock_survey.responses = []
        mock_store.get_survey_by_id.return_value = mock_survey

        update_details = {
            "title": sample_survey["title"],
            "prompt": "How are you?",
            "close_date": sample_survey["close_date"]
        }
        sample_survey["prompt"] = "How are you?"
        mock_store.update_survey.return_value = sample_survey
        survey = services.update_survey(1, update_details)

        assert survey.id == 1
        assert survey.title == "Mid-Year Check-in"
        assert survey.prompt == "How are you?"
        assert survey.department == "Marketing"
        assert survey.open_date == date(2026, 6, 20)
        assert survey.close_date == date(2026, 10, 20)

        mock_store.get_survey_by_id.assert_called_once()
        mock_store.commit_change.assert_called_once()

def test_update_survey_blocked_by_responses(sample_survey):
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 1
        mock_survey = Mock()
        mock_survey.configure_mock(**sample_survey)
        mock_survey.responses = [{}] # represents one response
        mock_store.get_survey_by_id.return_value = mock_survey

        update_details = {
            "title": sample_survey["title"],
            "prompt": "How are you?",
            "close_date": sample_survey["close_date"]
        }
        sample_survey["prompt"] = "How are you?"
        mock_store.update_survey.return_value = sample_survey
        with pytest.raises(SurveyUnmodifiableError):
            survey = services.update_survey(1, update_details)

def test_delete_survey_success(sample_survey):
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 1
        mock_store.get_survey_by_id.return_value = sample_survey

        services.delete_survey(1)

        mock_store.get_survey_by_id.assert_called_once()
        mock_store.delete_survey.assert_called_once_with(sample_survey)

def test_delete_survey_not_found():
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        mock_store.get_survey_by_id.return_value = None

        with pytest.raises(SurveyNotFoundError):
            services.delete_survey(1)

def test_get_all_responses(sample_responses):
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        mock_store.get_all_responses.return_value = sample_responses

        responses = services.get_all_responses(1)

        assert responses[0].sentiment == "POSITIVE" # first response identifying field
        assert responses[1].sentiment == "NEGATIVE" # second response identifying field

        mock_store.get_all_responses.assert_called_once()

def test_get_all_responses_none():
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        mock_store.get_all_responses.return_value = []

        responses = services.get_all_responses(2)

        assert len(responses) == 0

        mock_store.get_all_responses.assert_called_once()

@patch("employee_survey_analyzer.surveys.services.date")
def test_survey_not_yet_open(mock_date, sample_survey):
    mock_date.today.return_value = date(2026, 9, 1)

    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 1
        sample_survey["open_date"] = "2026-09-02"
        mock_store.get_survey_by_id.return_value = sample_survey

        with pytest.raises(SurveyUnavailableError, match=escape("Survey (ID=1) not open yet")):
            services.validate_response(1)

@patch("employee_survey_analyzer.surveys.services.date")
def test_survey_closed(mock_date, sample_survey):
    mock_date.today.return_value = date(2026, 9, 1)

    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 1
        sample_survey["close_date"] = "2026-08-02"
        mock_store.get_survey_by_id.return_value = sample_survey

        with pytest.raises(SurveyUnavailableError, match=escape("Survey (ID=1) already closed")):
            services.validate_response(1)

@patch("employee_survey_analyzer.surveys.services.analyze_sentiment")
@patch("employee_survey_analyzer.surveys.services.redact_pii")
@patch("employee_survey_analyzer.surveys.services.date")
def test_create_response_success(mock_date, mock_redact, mock_sentiment, sample_survey):
    mock_date.today.return_value = date(2026, 9, 1)

    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 1
        mock_store.get_survey_by_id.return_value = sample_survey # validate_response() calls get_survey_by_id()

        mock_store.create_response.side_effect = _mock_set_created_at # both id and created_at are created by DB
        mock_redact.return_value = "My manager, [REDACTED], has been super supportive in onboarding me! He listens to my concerns and is flexible when I feel like I need more time to gradually ramp up to the tasks we perform here."
        mock_sentiment.return_value = ("POSITIVE", 0.99)

        response = services.create_response(1, {"body": "My manager, John Smith, has been super supportive in onboarding me! He listens to my concerns and is flexible when I feel like I need more time to gradually ramp up to the tasks we perform here."})

        assert response.id == 1
        assert response.survey_id == 1
        assert response.sentiment == "POSITIVE"
        assert response.confidence_score == 0.99

        mock_store.get_survey_by_id.assert_called_once()
        mock_store.create_response.assert_called_once()
        mock_store.commit_change.assert_called_once()

@patch("employee_survey_analyzer.surveys.services.analyze_sentiment")
@patch("employee_survey_analyzer.surveys.services.redact_pii")
@patch("employee_survey_analyzer.surveys.services.date")
def test_create_response_aws_error(mock_date, mock_redact, mock_sentiment, sample_survey):
    mock_date.today.return_value = date(2026, 9, 1)

    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        sample_survey["id"] = 1
        mock_store.get_survey_by_id.return_value = sample_survey # validate_response() calls get_survey_by_id()

        mock_store.create_response.side_effect = _mock_set_created_at # both id and created_at are created by DB
        mock_redact.side_effect = BotoCoreError() # any error with Comprehend, such as failing redaction, will stop request
        mock_sentiment.return_value = ("POSITIVE", 0.99)

        with pytest.raises(BotoCoreError):
            services.create_response(1, {"body": "My manager, John Smith, has been super supportive in onboarding me! He listens to my concerns and is flexible when I feel like I need more time to gradually ramp up to the tasks we perform here."})

@pytest.mark.parametrize("body", [{}, {"confirm_deletion": "false"}])
def test_delete_response_invalid_auth(body):
    with pytest.raises(InvalidAuthorizationError):
        services.validate_response_deletion(body)

def test_delete_response_success(sample_responses):
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        response = Response(**sample_responses[0].model_dump())
        mock_store.get_response_by_id.return_value = response
        body = {"confirm_deletion": "true"}

        services.delete_response(1, body)

        mock_store.get_response_by_id.assert_called_once()
        mock_store.delete_response.assert_called_once_with(response)

def test_delete_response_not_found():
    with patch("employee_survey_analyzer.surveys.services.store") as mock_store:
        mock_store.get_response_by_id.return_value = None
        body = {"confirm_deletion": "true"}

        with pytest.raises(SurveyNotFoundError):
            services.delete_response(1, body)