"""add audit table

Revision ID: 69103592a777
Revises: 6ae71ee07b63
Create Date: 2026-09-03 12:45:51.234383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69103592a777'
down_revision = '6ae71ee07b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('correlation_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_table')
    # ### end Alembic commands ###
