"""add response sentiment

Revision ID: 6ae71ee07b63
Revises: bb2be572d062
Create Date: 2026-08-31 10:09:20.660586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae71ee07b63'
down_revision = 'bb2be572d062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
